[WIP] Add positional information
Bogdanp/elm-ast pull request #84
Opened 2017-08-29 19:49 UTC by Baransu

#### Huge thanks to @joeandaverde for creating most of what is implemented in this PR in the first place. 

All Expressions and Statements now have Meta as last argument `{ line: Int, column: Int }`.
Almost all types are converted contain meta information except:
- [ ] TypeApplication
- [ ] Application
- [ ] BinOp
- [ ] Variable

They are advanced because of
- partial application in case of `TypeApplication` and `Application`
- creating in place `Variable` and `BinOp` types

I was trying implement Meta for those as well but I've failed lacking knowledge and full understanding of `parser-combinators` as well as advanced Elm. That why I'm creating this WIP PR,  counting on your support. 

*** 
Contains also commits from #83.
Fixes: #13

2017-09-09 21:21 UTC, wende requested changes

2017-09-09 21:21 UTC, wende commented on tests/Expression.elm
> +module Expression
It shouldn't be a part of this PR. It solves different issue

2017-09-09 21:21 UTC, wende commented on tests/Helpers.elm
> +module Helpers
Ditto

2017-09-09 21:21 UTC, wende commented on tests/Multiline.elm
> +module Multiline exposing (application)
Ditto

2017-09-27 20:59 UTC, Baransu commented
### Support for all types has arrived!!! 🎉
Huge shoutout to @joeandaverde and @laslowh for their work on making this changes possible.
This is huge breaking change and I'm looking forward on any feedback.

2017-09-27 21:24 UTC, wende requested changes
Outstanding work!
Few styling comments on my end. We also need to consider some [half]measure to solve the line numbering bug in application before releasing it in next major version

2017-09-27 21:24 UTC, wende commented on src/Ast/Expression.elm
> +                                ((,)
Please try to avoid splitting arguments to next line
Backpipe (<|) twice could do the job here

2017-09-27 21:24 UTC, wende commented on src/Ast/Expression.elm
> +                                    )
Ditto. Could rewritten to something similar to
```
withMeta <|
  Record <$> braces <| comaSeparated <| withMeta <| (\a m -> (a, Variable [a], m) <$> loName)
```

2017-09-27 21:24 UTC, wende commented on src/Ast/Expression.elm
> +                    (term ops)
Ditto

2017-09-27 21:24 UTC, wende commented on src/Ast/Expression.elm
> +                remO
Oh god 😮 Ditto

2017-09-27 21:24 UTC, wende commented on src/Ast/Expression.elm
> +                            )
Ditto

2017-09-27 21:24 UTC, wende commented on tests/Multiline.elm
> +                        )
Apart from the bug of line numbers (Every argument's line being 1 too small apart from the last one) that I assume is coming from Combine dependency rather then this codebase, the isApplication` could be slightly modified to produce this output

2017-12-19 14:15 UTC, laslowh commented
Just checking in on this.  Has any progress on the line numbering bug been made?

2017-12-19 14:29 UTC, wende commented
@laslowh So the issue is with lines starting from index 0 (rather than 1) then jumping straight to 2, and treating the last line in the expression as the same as one before. So essentially instead of getting 1,2,3,4,5, we're getting 0,2,3,4,4. No idea what's the cause
Could use a little work on that. I might try to take a look this weekend

CC. @Baransu

2017-12-19 17:24 UTC, joeandaverde commented
Looks like the line numbering issues were addressed:

https://github.com/elm-community/parser-combinators/blob/master/CHANGELOG.md

I've started work on fixing the tests and upgrading the package.

2017-12-19 17:26 UTC, joeandaverde commented
https://github.com/Baransu/elm-ast/pull/2

2018-07-19 14:50 UTC, paulsonnentag commented
Is this PR still active? If not could I help getting this feature merged?

2018-07-19 20:33 UTC, wende commented
@paulsonnentag there's nobody actively working on this. It'd be great if you tried your shot

2018-07-24 14:19 UTC, paulsonnentag commented
@joeandaverde I've checked out your latest commit, but it seems like there are still a lot of cases where the line/column number is not correct. Do you have any tips on what the problem could be? Otherwise, I'll have to dig deeper into the code.

2018-10-27 17:00 UTC, wende commented
I've started working on this issue this weekend and it looks like it will see a closure soon

2018-10-27 19:31 UTC, baransu commented
@wende If you need any help, let me know 😃

2019-04-25 10:05 UTC, wende commented
Closed in favour of #99

2019-04-25 10:05 UTC, closed without merging